Error: Unable to resolve image URL from source (null)
It looks like Image in this case is null, meaning the user doesn't have an image. To prevent this from happening, you can check whether or not the user has an image before rendering the image tag.